// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1i15KrxMR9M-1uu7_IO6CYz_EsWcaq3I',
    appId: '1:885215594778:web:7a1ec1c39006e7e45e44a3',
    messagingSenderId: '885215594778',
    projectId: 'ecomerce-87a68',
    authDomain: 'ecomerce-87a68.firebaseapp.com',
    storageBucket: 'ecomerce-87a68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkq9KFm4BljcWjyQAjCbk3ruh_8g6o4jc',
    appId: '1:885215594778:android:1b8e0a49fd4d9be75e44a3',
    messagingSenderId: '885215594778',
    projectId: 'ecomerce-87a68',
    storageBucket: 'ecomerce-87a68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJSOW4yGRsnBV7uBBfsxe68qrfxC52mqg',
    appId: '1:885215594778:ios:151f7452fcbd8f9d5e44a3',
    messagingSenderId: '885215594778',
    projectId: 'ecomerce-87a68',
    storageBucket: 'ecomerce-87a68.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJSOW4yGRsnBV7uBBfsxe68qrfxC52mqg',
    appId: '1:885215594778:ios:151f7452fcbd8f9d5e44a3',
    messagingSenderId: '885215594778',
    projectId: 'ecomerce-87a68',
    storageBucket: 'ecomerce-87a68.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1i15KrxMR9M-1uu7_IO6CYz_EsWcaq3I',
    appId: '1:885215594778:web:7dff455da626c1915e44a3',
    messagingSenderId: '885215594778',
    projectId: 'ecomerce-87a68',
    authDomain: 'ecomerce-87a68.firebaseapp.com',
    storageBucket: 'ecomerce-87a68.appspot.com',
  );
}
